### PR TITLE
fix issue loading ox-slimhtml

### PR DESCRIPTION
**Pull request by benoitj**
temp solution leveraging straight to fetch from github

### CODE REVIEW

**Comment by benoitj** [comment]
this does not work either.

what if we had a submodule pointing to the original github and then all we need is to add it to the load path?

**Comment by benoitj** [comment]
using submodules works.

needed to update checks to fetch submodules on checkout.

possibly need to update deployment job to do the same

**Comment by daviwil** [comment]
My opinion is to just commit the source file of ox-slimhtml (for now) instead of adding a submodule (submodules are kinda annoying).  I reached out to the author of ox-slimhtml, he said he will try to finish the job of getting the package merged into Org.  In the meantime, including that source in our repo is good enough.

Here's how I did it for systemcrafters.cc: https://git.sr.ht/~systemcrafters/site/commit/4eaefecd7d7ef11c1f57f7a834f60df6e6fe2185

**Comment by daviwil** [comment]
Thanks @benoitj!

**Pull request merged**
