### PR TITLE
Add links to playlists

### PR DESCRIPTION
**Pull request by bkaestner**
There's nothing wrong with pointing back to your own content 😄.

### CODE REVIEW

**Comment by daviwil** [comment]
I didn't even think to come back and put the links here, thanks for doing it!

**Comment by bkaestner** [comment]
> I didn't even think to come back and put the links here, thanks for doing it!

You're welcome 🙂. I was looking for `my/org-roam-find-node`, but that was only linked from the video. I wonder whether the show notes should also get linked.

**Comment by bkaestner** [comment]
Aaaand I just noticed that there's an overview site on https://systemcrafters.net/build-a-second-brain-in-emacs/. Maybe we should add a link to the overview/index page as well?

**Comment by daviwil** [comment]
Could be useful!

**Comment by minikN** [comment]
I think at the moment SC has different hubs of knowlegde, there's the wiki, the website in general that has bit and pieces of information, the videos (obviously), show notes, smaller wikis from series (EFS for example) and maybe more.

I think the wiki could become some sort of entry for everything (apart from the videos itself of course) that, apart from wiki articles written by community members also accumulates Information from the other hubs and presents it in an organized manner.

At least that's what I envision the wiki to be. That doesn't mean that there shouldn't be any other source of information, but the wiki, at least in my opinion, should be the place to start search for stuff I want to get information about.

For that we need to change it's structure abit to make it more user friendly. I'm currently brainstorming how to do this and experiment with ideas. Unfortunately my time at the moment is limited so a PR will take some time.

**Comment by daviwil** [comment]
Sounds good to me!  Don't worry about how long it takes, I appreciate the help!

**Pull request merged**
