### PR TITLE
 Add installation guides, add FAQs, update index page for GNU Guix

### PR DESCRIPTION
**Pull request by TheCatster**
This PR seeks to add two installation guides for GNU Guix, a recommended nonguix one, and a free (as in freedom) standard CLI installation. The GNU Guix index page has also been overhauled, including some quick information, references to the FAQs page, and (eventually) some featured articles and news related to GNU Guix.

The FAQs page holds just that, frequently asked questions related to GNU Guix as both an OS and a package manager, how to use nonfree software on GNU Guix, and questions along those lines.

### CODE REVIEW

**Comment by daviwil** [comment]
I love it so far! ✨

**Comment by TheCatster** [comment]
Thanks! `<placeholder>` is used throughout the document so I have a fast way to jump to places I need to add links.

**Comment by SqrtMinusOne** [comment]
I'd suggest adding a section to the installation guide called "References" or "Further reading", with contents around:

- [Installation in Guix manual](https://guix.gnu.org/manual/devel/en/html_node/Installation.html#Installation)
- [Nonguix repo](https://gitlab.com/nonguix/nonguix/)

like it's done in Wikipedia.

**Comment by TheCatster** [comment]
Great idea, on it!

**Comment by TheCatster** [comment]
Added, let me know if that's what you were thinking, @SqrtMinusOne.

**Comment by SqrtMinusOne** [comment]
@TheCatster Yes, that's what I was thinking about.

I've just noticed that I posted the wrong link for the manual though, it should've been this one - [System Installation](https://guix.gnu.org/manual/devel/en/html_node/System-Installation.html#System-Installation)

**Comment by TheCatster** [comment]
Fixed! That should leave me with just the general recommendations, so far these are my ideas:

- [ ] Window Managers and Desktop Environments
- [ ] Browsers
- [ ] Music
- [ ] Full Linux Kernel (if they didn't do it earlier but want to now)

Each of these will link out to the respective page when written. Any other ideas? Feels sparse. I read the Arch Wiki's way of doing that, but honestly that is so much info at once it doesn't seem to be useful "general recommendations." (don't get me wrong, love the Arch Wiki, but that general recommendations page is a lot)

**Comment by daviwil** [comment]
Those all sound great!  I'd say maybe we could go ahead and merge the part of the work that's done right now and add the rest in additional PRs?  It'd be nice to have the Guix content started on the site

**Comment by TheCatster** [comment]
Absolutely! If you are okay with it, I'll merge now.

**Comment by daviwil** [comment]
Go for it!

**Pull request merged**
