### PR TITLE
WIP: Overhaul UX

### LINKED ISSUE #4: Overhaul UX and improve site indexing
Currently the UX is definitely clunky, and there is no indexing. This renders our search function useless; setting up a site map is crucial, and should help with this. Pages like the recently merged "browsers" aren't even accessible easily, and with the current layout have no reasonable way to be incorporated. I take inspiration from the handling of the Debian and Arch wikis, however incorporating the existing style of the site. 

This is a fairly high priority, and is already being worked on.

### PR DESCRIPTION
**Pull request by TheCatster**
Closes #4. See there for more details, but this includes hooking in the sitemap, fixing the flow of the site, and (possibly) adding in better search.

### CODE REVIEW

**Comment by TheCatster** [comment]
Sitemap currently looks like this: 
image

Any other details we want to add?

**Comment by TheCatster** [comment]
And after a while of tweaking, this is how the index page looks now, I think it's more appealing and organised:
image

**Comment by TheCatster** [comment]
Accidentally clicked ready for review, my apologies

**Comment by TheCatster** [comment]
I'd like to change the colour of the links to match the above, how would I go about changing/overriding the CSS? Currently it is using the CSS from your site, and I just cloned that locally. 

Also, I've decided this PR has been open too long and is too ambitious, I'd rather have many good changes as needed instead of continuously merging as new things are added (especially on the Emacs side). I'll open another PR once I am ready to work on the Emacs/Guix index UX.

**Comment by daviwil** [comment]
The changes you made look great to me so far!

**Comment by TheCatster** [comment]
I got busy with work and haven’t had the chance to PR the CSS to sourcehut, but I’ll push the main changes here. Have written down a reminder in Org to do so later :D

**Pull request merged**
