### PR TITLE
Add Twitch.tv IRC instructions

### PR DESCRIPTION
**Pull request by duckwork**
Also converted to Unix line endings.

### CODE REVIEW

**Comment by TheCatster** [comment]
Looks good to me, although to be a stickler we've always had no newline between the heading and content. Seems as though maybe it was auto-formatted, but it redid the entire file.

**Comment by duckwork** [comment]
What's the best way to correct the issue? I'm not 100% sure how to rebase (but I can try to learn), or I can add another commit ?

**Comment by TheCatster** [comment]
Honestly you can just do another commit, I don't think we care too much here. In a larger codebase I'd complain about rebasing or what-not.

**Review by TheCatster — CHANGES_REQUESTED** [review]
Just fix what we talked about, I forgot to include it as a review.

**Comment by duckwork** [comment]
Made changes as requested. Thank you for the understanding!

**Comment by daviwil** [comment]
Thanks Case!

**Pull request merged**
